### ISSUE TITLE
大佬您好，这个py服务无法启动怎么办吖

### ISSUE THREAD

**Issue by i-ccrru** [realhuhu/py-plugin#32]
![9{WB)$VL5Q`HET5NX82X 5L](https://user-images.githubusercontent.com/89241308/218249347-e0bee837-5a30-4993-abd2-2f19b9b4422d.png)
改了poetry的环境变量也无法启动

**Comment by i-ccrru** [comment]
按照搜到的类似结果处理之后报错
系统：Ubuntu 20.04.5 LTS aarch64

root@arm-64:/Bot/Yunzai-Bot/plugins/py-plugin# poetry run python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import nonebot
  File "/Bot/Yunzai-Bot/plugins/py-plugin/nonebot/__init__.py", line 4, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
root@arm-64:/Bot/Yunzai-Bot/plugins/py-plugin# poetry install
Installing dependencies from lock file

Package operations: 42 installs, 10 updates, 0 removals

  • Installing backports-zoneinfo (0.2.1): Failed

  CalledProcessError

  Command '['/root/.cache/pypoetry/virtualenvs/py-plugin-pAnUUoqv-py3.8/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/root/.cache/pypoetry/virtualenvs/py-plugin-pAnUUoqv-py3.8', '--no-deps', '/root/.cache/pypoetry/artifacts/4b/e4/32/8bbfaf54617c92f5dad281e53d1cf1e0985096627a8281f239e89a4f4e/backports.zoneinfo-0.2.1.tar.gz']' returned non-zero exit status 1.

  at /usr/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/py-plugin-pAnUUoqv-py3.8/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/root/.cache/pypoetry/virtualenvs/py-plugin-pAnUUoqv-py3.8', '--no-deps', '/root/.cache/pypoetry/artifacts/4b/e4/32/8bbfaf54617c92f5dad281e53d1cf1e0985096627a8281f239e89a4f4e/backports.zoneinfo-0.2.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/4b/e4/32/8bbfaf54617c92f5dad281e53d1cf1e0985096627a8281f239e89a4f4e/backports.zoneinfo-0.2.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: backports.zoneinfo
    Building wheel for backports.zoneinfo (pyproject.toml): started
    Building wheel for backports.zoneinfo (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Building wheel for backports.zoneinfo (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [41 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-aarch64-cpython-38
        creating build/lib.linux-aarch64-cpython-38/backports
        copying src/backports/__init__.py -> build/lib.linux-aarch64-cpython-38/backports
        creating build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_zoneinfo.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_version.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_tzpath.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_common.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/__init__.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        running egg_info
        writing src/backports.zoneinfo.egg-info/PKG-INFO
        writing dependency_links to src/backports.zoneinfo.egg-info/dependency_links.txt
        writing requirements to src/backports.zoneinfo.egg-info/requires.txt
        writing top-level names to src/backports.zoneinfo.egg-info/top_level.txt
        reading manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        /tmp/pip-build-env-80ezclku/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
          warnings.warn(msg, warning_class)
        warning: no files found matching '*.png' under directory 'docs'
        warning: no files found matching '*.svg' under directory 'docs'
        no previously-included directories found matching 'docs/_build'
        no previously-included directories found matching 'docs/_output'
        adding license file 'LICENSE'
        adding license file 'licenses/LICENSE_APACHE'
        writing manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
        copying src/backports/zoneinfo/__init__.pyi -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/py.typed -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        running build_ext
        building 'backports.zoneinfo._czoneinfo' extension
        creating build/temp.linux-aarch64-cpython-38
        creating build/temp.linux-aarch64-cpython-38/lib
        aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/root/.cache/pypoetry/virtualenvs/py-plugin-pAnUUoqv-py3.8/include -I/usr/include/python3.8 -c lib/zoneinfo_module.c -o build/temp.linux-aarch64-cpython-38/lib/zoneinfo_module.o -std=c99
        lib/zoneinfo_module.c:1:10: fatal error: Python.h: 没有那个文件或目录
            1 | #include "Python.h"
              |          ^~~~~~~~~~
        compilation terminated.
        error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for backports.zoneinfo
  Failed to build backports.zoneinfo
  ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects
  

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /root/.cache/pypoetry/artifacts/4b/e4/32/8bbfaf54617c92f5dad281e53d1cf1e0985096627a8281f239e89a4f4e/backports.zoneinfo-0.2.1.tar.gz

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│

**Comment by 18134583848** [comment]
手机版云崽弄这个的依赖下不好
